#!/bin/bash

set -e

DERIVED_DATA_PATH=$1
BUNDLE_IDENTIFIER='im.rime.inputmethod.Squirrel'
INSTALL_LOCATION='/Library/Input Methods'

cd "$(dirname $0)"
source common.sh

pkgbuild \
    --root "${PROJECT_ROOT}/${DERIVED_DATA_PATH}/Build/Products/Release" \
    --filter '.*\.swiftmodule$' \
    --component-plist Squirrel-component.plist \
    --identifier "${BUNDLE_IDENTIFIER}" \
    --version "$(get_app_version)" \
    --install-location "${INSTALL_LOCATION}" \
    --scripts "${PROJECT_ROOT}/scripts" \
    Squirrel-component.pkg

# 卸载器组件包（安装到 /Applications，安装界面里可勾选）
UNINSTALLER_ROOT="${PROJECT_ROOT}/${DERIVED_DATA_PATH}/uninstaller-root"
bash make_uninstaller "$UNINSTALLER_ROOT" "$(get_app_version)"
pkgbuild \
    --root "$UNINSTALLER_ROOT" \
    --component-plist Uninstaller-component.plist \
    --identifier "${BUNDLE_IDENTIFIER}.uninstaller" \
    --version "$(get_app_version)" \
    --install-location /Applications \
    Squirrel-Uninstaller-component.pkg

sed "s/@VERSION@/$(get_app_version)/" Distribution > Distribution-versioned.xml

productbuild \
    --distribution Distribution-versioned.xml \
    --package-path . \
    --resources . \
    Squirrel.pkg

rm Distribution-versioned.xml

rm Squirrel-component.pkg
rm Squirrel-Uninstaller-component.pkg
